---
install_ondemand_dex: true
httpd_auth:
- AuthType openid-connect
- Require valid-user
oidc_settings:
  OIDCSSLValidateServer: "Off" # Required due to self signed certs
dex_uri: /dex
# ldapsearch query to help troubleshooting LDAP for AD
# ldapsearch -x -H ldap://adds -D ldap_access@hpc.azure -b 'cn=users,dc=hpc,dc=azure' -w 'password' -s sub "(&(objectClass=person)(userPrincipalName=hpcadmin@hpc.azure))"
# https://dexidp.io/docs/connectors/ldap/
dex_settings: |
  dex:
    connectors: 
      - type: ldap
        id: ldap
        name: ActiveDirectory
        config:
          host: '{{ ldap_host }}'
          insecureNoSSL: true
          insecureSkipVerify: false
          startTLS: true
          bindDN: '{{ bind_DN }}'
          bindPW: '{{ bind_PW }}'
          userSearch:
            baseDN: '{{ user_base_DN }}'
            filter: "(objectClass=person)"
            username: userPrincipalName
            idAttr: DN
            emailAttr: userPrincipalName
            nameAttr: cn
            preferredUsernameAttr: sAMAccountName
          groupSearch:
            baseDN: '{{ group_base_DN }}'
            filter: "(objectClass=group)"
            userMatchers:
              - userAttr: DN
                groupAttr: member
            nameAttr: cn