---
ood_install_apps:
  cc_connect:
    repo: '{{ git_url }}'
    version: main
  ccw_codeserver:
    repo: 'https://github.com/xpillons/ccw_codeserver.git'
    version: main
  ccw_jupyter:
    repo: 'https://github.com/xpillons/ccw_jupyter.git'
    version: main

ood_apps:
  dashboard:
    env:
      ood_bc_dynamic_js: true
#     file_upload_max: "{{ondemand.file_upload_max | default(omit)}}"

host_regex: '[^./]+'
node_uri: '/node'
rnode_uri: '/rnode'
#pun_pre_hook_root_cmd: /etc/ood/config/pun_pre_hook.sh

pun_custom_env:
  OOD_DASHBOARD_TITLE: "Open OnDemand for Azure CycleCloud"
#  OOD_DASHBOARD_LOGO: "/public/logo.png"
  OOD_BRAND_BG_COLOR: "#0078d4"
  OOD_BRAND_LINK_ACTIVE_BG_COLOR: "#212529"
  OOD_JOB_NAME_ILLEGAL_CHARS: "/"
#  OOD_ALLOWLIST_PATH: "{{ondemand.whitelist_path | default('/')}}"

# See https://osc.github.io/ood-documentation/latest/customization.html#pinning-applications-to-the-dashboard
pinned_apps:
  - sys/shell
  - category: 'Interactive Apps'
