---
install_ondemand_dex: false
httpd_auth:
- AuthType openid-connect
- Require valid-user
# oidc_settings:
#   OIDCSSLValidateServer: "Off" # Required due to self signed certs

ood_auth_openidc:
  OIDCProviderMetadataURL: 'https://sts.windows.net/{{tenant_id}}/.well-known/openid-configuration'
  OIDCClientID: '{{ client_id }}'
  OIDCClientSecret: '{{ client_secret }}'
  OIDCRemoteUserClaim: 'unique_name'
  OIDCScope: 'openid profile email groups'
  OIDCCryptoPassphrase: '{{ client_secret }}'
  OIDCPassIDTokenAs: 'serialized'
  OIDCPassRefreshToken: 'On'
  OIDCPassClaimsAs: 'environment'
  OIDCStateMaxNumberOfCookies: [7, true]



# dex_uri: /dex
# dex:
#   connectors:
#     - type: microsoft
#       id: microsoft
#       name: Microsoft
#       config:
#         clientID: '{{ client_id }}'
#         clientSecret: '{{ client_secret }}'
#         redirectURI: 'https://{{ var_ood_fqdn }}/dex/callback'
#         tenant: '{{ tenant_id }}'
#oidc_remote_user_claim: "email"
logout_redirect: "/oidc?logout=https%3A%2F%2F {{ ood_fqdn }}"
oidc_uri: /oidc

user_map_match: '^([^@]+)@microsoft.com$'
