---
- name: Make sure we have the latest root certificates in AlmaLinux
  yum:
    name: ca-certificates
    state: latest
    lock_timeout : 180

- name: Auth Basic specific installation 
  block:
    - name: install pwauth and apache2 modules
      yum:
        name:
          - mod_authnz_external
          - mod_authnz_pam
          - pwauth
    - name: set variables for AlmaLinux
      set_fact:
        custom_vhost_directives:
          - AddExternalAuth pwauth /usr/bin/pwauth
          - SetExternalAuthMethod pwauth pipe
  when: auth_method == "Basic"

- name: Auth LDAP specific installation 
  block:
    - name: Install LDAP search utility
      yum:
        name: openldap-clients
        state: latest
  when: auth_method == "LDAP"
