---
- name: Make sure we have the latest root certificates in Ubuntu
  apt:
    name: ca-certificates
    state: latest

- name: Auth Basic specific installation 
  block:
    - name: install pwauth and apache2 modules
      apt:
        name:
          - libapache2-mod-authnz-pam
          - libapache2-mod-authnz-external
          - pwauth
    - name: set variables for Ubuntu
      set_fact:
        custom_vhost_directives:
          - AddExternalAuth pwauth /usr/sbin/pwauth
          - SetExternalAuthMethod pwauth pipe
  when: auth_method == "Basic"


- name: Install LDAP search utility
  apt:
    name: ldap-utils
    state: latest
  when: auth_method == "LDAP"

